### ISSUE TITLE
Startup issue: all i have is the little owl in the corner.. It's like it isn't getting data?

### ISSUE THREAD

**Issue by bureus** [bureus/MMM-Nightscout#1]
Writer: @infallibleapex

all i have is the little owl in the corner.. It's like it isn't getting data?

where does the logging happen and does this work with the herokuapp.com deployments?

I was SUPER excited to see this app as I couldn't get the page to load in an iFrame on MagicMirror

(sorry to post here but I couldn't find another way to contact you) :)

**Comment by bureus** [comment]
Also could you give me your version of Nightscout that you are running? Should be under Meny -> About

**Comment by bureus** [comment]
Writer: @infallibleapex
nightscout
version 0.11.1

[{"_id":"5c896908db57e7343f587b7e","device":"xDrip-DexcomG5","date":1552509190096,"dateString":"2019-03-13T16:33:10.096-0400","sgv":221,"delta":-1.49,"direction":"Flat","type":"sgv","filtered":215168,"unfiltered":214560,"rssi":100,"noise":1,"sysTime":"2019-03-13T16:33:10.096-0400"},{"_id":"5c8967dcdb57e7343f58740a","device":"xDrip-DexcomG5","date":1552508889953,"dateString":"2019-03-13T16:28:09.953-0400","sgv":222,"delta":-0.954,"direction":"Flat","type":"sgv","filtered":217408,"unfiltered":215712,"rssi":100,"noise":1,"sysTime":"2019-03-13T16:28:09.953-0400"},{"_id":"5c8966b0db57e7343f586d66","device":"xDrip-DexcomG5","date":1552508590549,"dateString":"2019-03-13T16:23:10.549-0400","sgv":223,"delta":-2.863,"direction":"Flat","type":"sgv","filtered":221312,"unfiltered":216448,"rssi":100,"noise":1,"sysTime":"2019-03-13T16:23:10.549-0400"}]

edit: thanks for the response, we could move the convo to issues if you'd like :D

**Comment by bureus** [comment]
@infallibleapex, i have used your sensor data as mock and the app is working in my setup. Could you also share me the response you get when querying https://baseURL/api/v1/profile? Then i have all the data i need in order to run my app as you :) 

Second can you verify that you have perfomed npm install after cloning it into the modules folder? 

BR

**Comment by infallibleapex** [comment]
[{"_id":"5c868533e69c47000410fa4f","defaultProfile":"Default","store":{"Default":{"dia":"3","carbratio":[{"time":"00:00","value":"30","timeAsSeconds":"0"}],"carbs_hr":"20","delay":"20","sens":[{"time":"00:00","value":"100","timeAsSeconds":"0"}],"timezone":"US/Eastern","basal":[{"time":"00:00","value":"0.1","timeAsSeconds":"0"}],"target_low":[{"time":"00:00","value":"0","timeAsSeconds":"0"}],"target_high":[{"time":"00:00","value":"0","timeAsSeconds":"0"}],"units":"mg/dl"}},"startDate":"2019-03-11T15:54:00.000Z","mills":"0","units":"mg/dl","created_at":"2019-03-11T15:56:43.442Z"}]

I did do the npm install in the MMM-Nightscout folder inside the modules folder.

**Comment by infallibleapex** [comment]
just saw this when manually re-starting MM2

Unhandled rejection ReferenceError: reject is not defined
    at /home/pi/MagicMirror/modules/MMM-Nightscout/node_helper.js:38:21
    at tryCatcher (/home/pi/MagicMirror/modules/MMM-Nightscout/node_modules/blue                                                                                      bird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/MagicMirror/modules/MMM-Night                                                                                      scout/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/MagicMirror/modules/MMM-Nightscout/node_                                                                                      modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/MagicMirror/modules/MMM-Nightscout/node                                                                                      _modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/MagicMirror/modules/MMM-Nightscout/node                                                                                      _modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/pi/MagicMirror/modules/MMM-Nightscout/node_modules                                                                                      /bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/MagicMirror/modules/MMM-Nightscout/node_modules/blu                                                                                      ebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/MagicMirror/modules/MMM-Nightscout/node_modu                                                                                      les/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/pi/MagicMirror/modules/MMM-Nightscout/                                                                                      node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by bureus** [comment]
@infallibleapex Interesting, could you look for "getServerConfig: failed when trying to retrieve data:" in the logs? Seems like if fails when trying to retrieve server configs.

**Comment by infallibleapex** [comment]
where do i find the log file?

**Comment by bureus** [comment]
Hm just before that exception you should see the logs. Printing them directly into the stdout. Could you also check what version of node you run? Just type

`
node -v
`

![image](https://user-images.githubusercontent.com/603643/54379595-fd8f4680-4689-11e9-9aec-285cca617ddf.png)

**Comment by infallibleapex** [comment]
Node -v
v9.11.2

looks like I may have botched the config... 
1:28:19 PM MMM-Nightscout: getServerConfig: failed when trying to retrive data: RequestError: Error: Invalid URI "jpt1d.herokuapp.comapi/v1/profile"

**Comment by bureus** [comment]
Yes :) please so what you should past in is 

`{
            module: "MMM-Nightscout",
            position: "top_left",
            config: {
                debug: true,
                baseUrl: 'https://jpt1d.herokuapp.com/'
            }
        },`

**Comment by infallibleapex** [comment]
1:53:45 PM MMM-Nightscout: getGlucoseData: failed when trying to retrive data: StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET //api/v1/entries.json</pre>\n</body>\n</html>\n"

**Comment by bureus** [comment]
Ah crap.. Sorry, typo in my code, please use: baseUrl: 'https://jpt1d.herokuapp.com'. I will release an updated version in 2 min. Just need to write relase notes.

**Comment by infallibleapex** [comment]
tried that and now I am getting (but it may be due to something else running on the pi?): 

Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080 }

**Comment by bureus** [comment]
Yeah, you can kill magic mirror process by doing: pm2 stop MagicMirror

![image](https://user-images.githubusercontent.com/603643/54381171-64fac580-468d-11e9-9fff-b909eb7c6aa6.png)


I have pushed a bugfix so please ensure the config is baseUrl: 'https://jpt1d.herokuapp.com'. And then get the latest code and install by doing: 

Run git pull inside ../modules/MMM-Nightscout/ folder.
Run npm install inside ../modules/MMM-Nightscout/ folder

**Comment by infallibleapex** [comment]
After the git pull and a reboot all is working.  Thank You

**Comment by bureus** [comment]
Great! :) Glad that i could help!
